//Init stuff
_crate = _this select 0;
["AmmoboxInit",[_crate,false,{true}]] spawn BIS_fnc_arsenal;

//Lists of items to include
_availableHeadgear = [
	"H_LIB_US_Helmet_Net_ns",
	"H_LIB_US_Helmet",
	"H_LIB_US_Helmet_Med_ns",
	"H_LIB_US_Helmet_os",
	"H_LIB_US_Helmet_NCO",
	"boina_cls",
	"boina_cls2",
	"boina_cls3",
	"boina_cls4",
	"boina_glocs",
	"boina_glocs2",
	"boina_negra",
	"boina_ocp",
	"boina_roja",
	"boina_eir",
	"boina_ama"
];

_availableGoggles = [
	"G_B_Diving"
];

_availableUniforms = [
	"U_LIB_US_Sergant",
	"U_LIB_US_Corp",
	"U_LIB_US_Private_1st",
	"fow_u_us_m37_02_private",
	"U_B_HeliPilotCoveralls",
	"U_B_Wetsuit",
	"U_B_PilotCoveralls"
];

_availableVests = [
	"fow_v_us_ab_garand_bandoleer",
	"LIB_M1_Garand",
	"fow_v_us_carbine_eng",
	"V_LIB_US_Vest_Medic",
	"fow_v_us_ab_bar",
	"fow_v_us_ab_asst_mg",
	"fow_v_us_thompson_nco_scr",
	"V_TacVest_blk",
	"V_RebreatherB"
];

_availableBackpacks = [
	"B_LIB_US_Backpack",
	"B_LIB_US_M36_Rocketbag_Empty",
	"B_LIB_US_M36_Bandoleer",
	"B_LIB_US_Backpack_Mk2",
	"B_LIB_US_M36",
	"B_LIB_US_M36_Rope",
	"B_Bergen_mcamo_F",
	"B_Bergen_tna_F",
	"B_Bergen_dgtl_F",
	"B_Bergen_hex_F",
	"ACE_NonSteerableParachute",
	"B_Carryall_cbr",
	"B_Carryall_mcamo",
	"B_Parachute",
	"B_Kitbag_mcamo",
	"B_rhsusf_B_BACKPACK",
	"tfw_ilbe_coy",
	"tfw_ilbe_gr",
	"tfw_ilbe_a_coy",
	"tfw_ilbe_a_gr",
	"tfw_ilbe_dd_coy",
	"tfw_ilbe_dd_gr",
	"tfw_ilbe_blade_coy",
	"tfw_ilbe_blade_gr"
];

_availableItems = [
    "ItemWatch",
    "ItemCompass",
    "ItemGPS",
    "ItemMap",
	"ItemRadio",
    "MineDetector",
    "Rangefinder",
	"Binocular",
    "Laserdesignator",
	"LIB_ACC_GL_M7",
	"LIB_ACC_M1_Bayo",
	"LIB_M1918A2_BAR_Bipod",
	"ACE_CableTie",
	"ACE_Banana",
	"ACE_ConcertinaWireCoil",
	"ACE_Clacker",
	"ACE_M26_Clacker",
	"ACE_DefusalKit",
	"ACE_DeadManSwitch",
	"ACE_Cellphone",
	"ACE_EarPlugs",
	"ACE_wirecutter",
	"ACE_MapTools",
	"ACE_atropine",
	"ACE_fieldDressing",
	"ACE_elasticBandage",
	"ACE_quikclot",
	"ACE_bloodIV",
	"ACE_bloodIV_500",
	"ACE_bloodIV_250",
	"ACE_bodyBag",
	"ACE_epinephrine",
	"ACE_morphine",
	"ACE_packingBandage",
	"ACE_personalAidKit",
	"ACE_plasmaIV",
	"ACE_plasmaIV_500",
	"ACE_plasmaIV_250",
	"ACE_salineIV",
	"ACE_salineIV_500",
	"ACE_salineIV_250",
	"ACE_surgicalKit",
	"ACE_tourniquet",
	"ACE_RangeTable_82mm",
	"ACE_NVG_Wide",
	"ACE_SpareBarrel",
	"ACE_Altimeter",
	"ACE_RangeCard",
	"ACE_key_master",
	"ACE_key_lockpick",
	"ACE_Sandbag_empty",
	"ACE_SpottingScope",
	"ACE_Tripod",
	"ACE_SpraypaintBlack",
	"ACE_SpraypaintBlue",
	"ACE_SpraypaintRed",
	"ACE_SpraypaintGreen",
	"ACE_EntrenchingTool",
	"ACE_adenosine",
	"ALIVE_Tablet",
	"ACRE_PRC343",
	"ACRE_PRC148",
	"ACRE_PRC152",
	"ACRE_PRC117F",
	"ACRE_PRC77",
	"ItemcTab",
	"ItemAndroid",
	"ItemcTabHCam",
	"ItemMicroDAGR",
	"ToolKit",
	"Medikit",
	"B_UavTerminal"

];

_availableMagazines = [
    "LIB_8Rnd_762x63",
	"LIB_8Rnd_762x63_t",
	"fow_1Rnd_m9a1",
	"fow_15Rnd_762x33",
	"LIB_20Rnd_762x63",
	"LIB_50Rnd_762x63",
	"LIB_30Rnd_45ACP",
	"LIB_5Rnd_762x63",
	"LIB_M1A1_Bazooka",
	"LIB_1Rnd_60mm_M6",
	"Chemlight_green",
    "Chemlight_red",
	"Chemlight_blue",
	"Chemlight_yellow",
	"ACE_Chemlight_HiOrange",
	"ACE_Chemlight_HiRed",
	"ACE_Chemlight_HiWhite",
	"ACE_Chemlight_HiYellow",
	"ACE_Chemlight_IR",
	"ACE_Chemlight_Orange",
	"ACE_Chemlight_White",
    "rhs_mag_m67",
    "SmokeShell",
    "SmokeShellRed",
    "SmokeShellGreen",
    "SmokeShellYellow",
    "SmokeShellPurple",
    "SmokeShellBlue",
    "SmokeShellOrange",
    "ATMine_Range_Mag",
    "APERSTripMine_Wire_Mag",
    "SatchelCharge_Remote_Mag",
    "DemoCharge_Remote_Mag",
    "Laserbatteries",
    "B_IR_Grenade",
	"ACE_HandFlare_White",
	"ACE_HandFlare_Red",
	"ACE_HandFlare_Green",
	"ACE_HandFlare_Yellow",
	"ACE_M84",
	"ACE_HuntIR_M203",
    "rhs_mine_M19_ammo",
	"1Rnd_HE_Grenade_shell",
	"UGL_FlareWhite_F",
	"UGL_FlareGreen_F",
	"UGL_FlareRed_F",
	"UGL_FlareCIR_F",
	"1Rnd_Smoke_Grenade_shell",
	"1Rnd_SmokeRed_Grenade_shell",
	"1Rnd_SmokeGreen_Grenade_shell",
	"1Rnd_SmokeYellow_Grenade_shell",
	"1Rnd_SmokePurple_Grenade_shell",
	"1Rnd_SmokeBlue_Grenade_shell"
];

_availableWeapons = [
	"LIB_M1_Garand",
	"LIB_M1A1_Bazooka",
	"LIB_M1_Garand_M7",
	"LIB_M1_Garand_Bayonet",
	"LIB_M1918A2_BAR",
	"LIB_M1919A6",
	"fow_w_m1a1_thompson",
	"LIB_M1903A4_Springfield",
	"ACE_VMH3"
];

//Populate with predefined items and whatever is already in the crate
[_crate,((backpackCargo _crate) + _availableBackpacks)] call BIS_fnc_addVirtualBackpackCargo;
[_crate,((itemCargo _crate) + _availableHeadgear + _availableGoggles + _availableUniforms + _availableVests + _availableItems)] call BIS_fnc_addVirtualItemCargo;
[_crate,((magazineCargo _crate) + _availableMagazines)] call BIS_fnc_addVirtualMagazineCargo;
[_crate,((weaponCargo _crate) + _availableWeapons)] call BIS_fnc_addVirtualWeaponCargo;