//Init stuff
_crate = _this select 0;
["AmmoboxInit",[_crate,false,{true}]] spawn BIS_fnc_arsenal;

//Lists of items to include
_availableHeadgear = [
	"usm_bdu_boonie_des",
	"usm_bdu_boonie_wdl",
	"usm_bdu_cap_des",
	"usm_bdu_cap_wdl",
	"usm_helmet_cvc",
	"usm_helmet_pasgt_d",
	"usm_helmet_pasgt_w",
	"usm_helmet_pasgt_g_d",
	"usm_helmet_pasgt_g_w",
	"usm_helmet_safety",
	"H_PilotHelmetFighter_B",
	"boina_cls",
	"boina_cls2",
	"boina_cls3",
	"boina_cls4",
	"boina_glocs",
	"boina_glocs2",
	"boina_negra",
	"boina_ocp",
	"boina_roja",
	"boina_eir",
	"boina_ama"
];

_availableGoggles = [
	"rhs_ess_black",
	"rhs_googles_clear",
	"rhs_googles_black",
	"rhs_googles_orange",
	"rhs_googles_yellow",
	"G_B_Diving",
	"rhs_scarf"
];

_availableUniforms = [
	"usm_bdu_w",
	"usm_bdu_d",
	"U_B_HeliPilotCoveralls",
	"U_B_Wetsuit",
	"U_B_PilotCoveralls"
];

_availableVests = [
	"usm_vest_pasgt_lbe_mg",
	"usm_vest_pasgt_lbe_gr",
	"usm_vest_pasgt_lbe_rmp",
	"usm_vest_pasgt_lbv_mg",
	"usm_vest_pasgt_lbv_gr",
	"usm_vest_pasgt_lbv_rmp",
	"usm_vest_safety",
	"V_TacVest_blk",
	"V_RebreatherB"
];

_availableBackpacks = [
	"usm_pack_m5_medic",
	"usm_pack_alice",
	"usm_pack_alice_prc119",
	"usm_pack_st138_prc77",
	"ACE_NonSteerableParachute",
	"ACE_TacticalLadder_Pack",
	"B_Parachute",
	"ACE_ReserveParachute"
];

_availableItems = [
	"hlc_optic_LRT_m14",
    "ItemWatch",
    "ItemCompass",
	"ItemRadio",
    "ItemMap",
	"tf_anprc148jem",
	"TFAR_rf7800str",
    "MineDetector",
	"Binocular",
	"rhsusf_ANPVS_14",
	"rhsusf_ANPVS_15",
	"ACE_IR_Strobe_Item",
	"ACE_CableTie",
	"ACE_Banana",
	"ACE_ConcertinaWireCoil",
	"ACE_Clacker",
	"ACE_M26_Clacker",
	"ACE_DefusalKit",
	"ACE_DeadManSwitch",
	"ACE_Cellphone",
	"ACE_Flashlight_MX991",
	"ACE_EarPlugs",
	"ACE_UAVBattery",
	"ACE_wirecutter",
	"ACE_MapTools",
	"ACE_atropine",
	"ACE_fieldDressing",
	"ACE_elasticBandage",
	"ACE_quikclot",
	"ACE_bloodIV",
	"ACE_bloodIV_500",
	"ACE_bloodIV_250",
	"ACE_bodyBag",
	"ACE_epinephrine",
	"ACE_morphine",
	"ACE_packingBandage",
	"ACE_personalAidKit",
	"ACE_plasmaIV",
	"ACE_plasmaIV_500",
	"ACE_plasmaIV_250",
	"ACE_salineIV",
	"ACE_salineIV_500",
	"ACE_salineIV_250",
	"ACE_surgicalKit",
	"ACE_tourniquet",
	"ACE_RangeTable_82mm",
	"ACE_NVG_Wide",
	"ACE_SpareBarrel",
	"ACE_Altimeter",
	"ACE_RangeCard",
	"ACE_key_master",
	"ACE_key_lockpick",
	"ACE_Sandbag_empty",
	"ACE_SpottingScope",
	"ACE_Tripod",
	"ACE_SpraypaintBlack",
	"ACE_SpraypaintBlue",
	"ACE_SpraypaintRed",
	"ACE_SpraypaintGreen",
	"ACE_EntrenchingTool",
	"ACE_adenosine",
	"ACE_DAGR",
	"ACE_microDAGR",
	"ItemMicroDAGR",
	"TFAR_microdagr",
	"ALIVE_Tablet",
	"ItemcTab",
	"ItemAndroid",
	"ItemcTabHCam",
	"ToolKit",
	"Medikit",
	"B_UavTerminal"
];

_availableMagazines = [
    "hlc_30rnd_556x45_EPR",
    "30Rnd_556x45_Stanag_Tracer_Red",
	"rhsusf_20Rnd_762x51_m993_Mag",
	"rhsusf_20Rnd_762x51_m118_special_Mag",
	"rhsusf_20Rnd_762x51_m62_Mag",
    "rhs_200rnd_556x45_M_SAW",
	"rhs_200rnd_556x45_T_SAW",
	"rhsusf_100Rnd_556x45_soft_pouch",
    "rhsusf_100Rnd_762x51",
    "rhs_ammo_M136_rocket",
	"rhs_m136_hedp_mag",
	"rhs_m136_hp_mag",
    "Chemlight_green",
    "Chemlight_red",
	"Chemlight_blue",
	"Chemlight_yellow",
	"ACE_Chemlight_HiOrange",
	"ACE_Chemlight_HiRed",
	"ACE_Chemlight_HiWhite",
	"ACE_Chemlight_HiYellow",
	"ACE_Chemlight_IR",
	"ACE_Chemlight_Orange",
	"ACE_Chemlight_White",
    "rhs_mag_m67",
    "SmokeShell",
    "SmokeShellRed",
    "SmokeShellGreen",
    "SmokeShellYellow",
    "SmokeShellPurple",
    "SmokeShellBlue",
    "SmokeShellOrange",
    "ATMine_Range_Mag",
    "APERSMine_Range_Mag",
    "APERSBoundingMine_Range_Mag",
    "SLAMDirectionalMine_Wire_Mag",
    "APERSTripMine_Wire_Mag",
    "ClaymoreDirectionalMine_Remote_Mag",
    "SatchelCharge_Remote_Mag",
    "DemoCharge_Remote_Mag",
    "Laserbatteries",
    "B_IR_Grenade",
	"rhsusf_mag_15Rnd_9x19_JHP",
	"ACE_HandFlare_White",
	"ACE_HandFlare_Red",
	"ACE_HandFlare_Green",
	"ACE_HandFlare_Yellow",
	"ACE_M84",
    "rhs_mine_M19_ammo",
	"rhs_mag_maaws_HEAT",
	"rhs_mag_maaws_HEDP",
	"rhs_mag_maaws_HE",
	"rhs_mag_smaw_HEAA",
	"rhs_mag_smaw_HEDP",
	"rhs_mag_smaw_SR",
	"rhs_mag_M433_HEDP",
	"1Rnd_HE_Grenade_shell",
	"UGL_FlareWhite_F",
	"UGL_FlareGreen_F",
	"UGL_FlareRed_F",
	"UGL_FlareCIR_F",
	"1Rnd_Smoke_Grenade_shell",
	"1Rnd_SmokeRed_Grenade_shell",
	"1Rnd_SmokeGreen_Grenade_shell",
	"1Rnd_SmokeYellow_Grenade_shell",
	"1Rnd_SmokePurple_Grenade_shell",
	"1Rnd_SmokeBlue_Grenade_shell",
	"rhs_m72a7_mag",
	"rhs_fgm148_magazine_AT",
	"rhs_mag_an_m14_th3",
	"rhs_mag_m7a3_cs"
];

_availableWeapons = [
	"ACE_VMH3",
    "hlc_rifle_Colt727",
	"hlc_rifle_M14",
	"hlc_rifle_M14_bipod",
    "rhs_weap_m240B",
    "rhs_weap_m249_pip",
	"hlc_rifle_Colt727_GL",
    "rhs_weap_M136",
	"rhs_weap_M136_hedp",
	"rhs_weap_M136_hp",
    "rhsusf_weap_m9",
	"rhs_weap_smaw_green",
	"rhs_weap_m72a7",
	"rhs_weap_maaws"
];

//Populate with predefined items and whatever is already in the crate
[_crate,((backpackCargo _crate) + _availableBackpacks)] call BIS_fnc_addVirtualBackpackCargo;
[_crate,((itemCargo _crate) + _availableHeadgear + _availableGoggles + _availableUniforms + _availableVests + _availableItems)] call BIS_fnc_addVirtualItemCargo;
[_crate,((magazineCargo _crate) + _availableMagazines)] call BIS_fnc_addVirtualMagazineCargo;
[_crate,((weaponCargo _crate) + _availableWeapons)] call BIS_fnc_addVirtualWeaponCargo;